# Generated by Django 4.0 on 2024-03-02 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_news_likes_news_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='value',
            field=models.CharField(choices=[('Like', True), ('Unlike', False)], default='Like', max_length=8, verbose_name='Значения'),
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(upload_to='lawyer/docs', verbose_name='Документ для потверждение')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('verify', models.BooleanField(default=False, verbose_name='Потвержден')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пользовател', to='newsapp.author')),
            ],
            options={
                'verbose_name': 'Юристы',
                'verbose_name_plural': 'Юрист',
            },
        ),
    ]
